### ISSUE TITLE
error: Compiling of app/vendor.ts failed. Cannot read property 'resolvedModule' of undefined 

### ISSUE THREAD

**Issue by davidjsalazarmoreno** [baptistedonaux/brunch-typescript#13]
Hi everyone, I'm trying to import libs in npm_modules via import keyword but had the next error: "error: Compiling of app/vendor.ts failed. Cannot read property 'resolvedModule' of undefined".

In my fork of the plugin I added some fixes than solve 'resolvedModule' issue.
https://github.com/davidjsalazarmoreno/brunch-typescript/blob/master/index.js#L14
https://github.com/davidjsalazarmoreno/brunch-typescript/blob/master/index.js#L58

But seems not work with latest versions of brunch plugin, the error aparently gone but not produce any javascript file from .ts with node_modules imports.

You can see the issue in this repository: https://github.com/davidjsalazarmoreno/brunch-typescript-issue 

**tsconfig**: https://github.com/davidjsalazarmoreno/brunch-typescript-issue/blob/master/tsconfig.json
**brunch-config**: https://github.com/davidjsalazarmoreno/brunch-typescript-issue/blob/master/brunch-config.js

Thanks everyone.

**Comment by speg** [comment]
I too am running into problems with the latest version. It cannot find any of my relative imports. I just isolated it to the `brunch-typescript` plugin now. I will try and see if I can come up with an isolated test after dinner. :hamburger:

**Comment by paulmillr** [comment]
@speg @davidjsalazarmoreno please revert to 1.8.1 for the time being.

**Comment by colinbate** [comment]
I agree revert to 1.8.1 for now. Even if this was working properly I suspect this change will be breaking for some people where certain errors were being ignored. Unfortunately this project doesn't really follow SemVer.

The TypeScript compiler spits out a bunch of errors when operating in single module mode which can be ignored, I've clearly not filtered out all of them. Let me look into this one.

**Comment by speg** [comment]
I've isolated it down to this [line](https://github.com/baptistedonaux/brunch-typescript/blob/master/transpile.js#L57)! I created a PR #14 that removes it. Maintains fix for #11 .

**Comment by colinbate** [comment]
OK, so, @davidjsalazarmoreno your issue isn't related to 1.8.2 (although at some point it probably would have given you trouble). Your issue is because you have `"moduleResolution": "node"` in your `tsconfig.json` file. It looks like this causes issues when using the compiler API as we do. Only it isn't reported as a compiler error, it is an actual runtime error, so it was bubbling up before this change. This is fixable on your part for the moment by removing that from your `tsconfig` or overriding it in the `brunch-config.js` file with:

```js
plugins: {
  brunchTypescript: {
    moduleResolution: undefined
  }
}
```

However, I will also make sure in future versions we strip this option out before passing them into the compiler.

@speg Your issue is similar but different. It is an error which occurs because we are compiling one module at a time and can be ignored. I'll fix that too.

**Comment by colinbate** [comment]
@paulmillr I'm not sure if these errors are really going to provide a huge value since they don't consider the other files when they compile. So if you have a type violation within a single file, it will flag that, but if you import a function from another file and use it with incorrect types, it doesn't know about it or raise any issue with that.

Similarly, it isn't aware of any globals or anything like that, so I'll have to ignore the "Can't find name" error outright.

I'm sure we can get the compiler to consider the other files, but that would slow things down a fair bit I would imagine.

At the moment, we can remove the errors, log them without failing, or we could allow people to specify error numbers they want to ignore.

/cc @baptistedonaux

**Comment by davidjsalazarmoreno** [comment]
@colinbate thank you, your solution works for me, the error has gone and de import works correctly, now I can import modules from node_modules.
